spring:
  application:
    name: dd-demo-exam
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    ru.mephi.dddemoexam: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log